apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: aspm-test
          artifact-id: 488e5dc3-397c-4d8c-b772-602ba24347e3
          target-environment: Pre-prod
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: aspm-test
          artifact-id: 11ca354b-97ba-4af3-a173-cedace4e4250
          target-environment: qa
