apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: aspm-test
          artifact-id: 37c23744-36e6-48ba-a77c-f7b44ee574bb
          target-environment: Pre-prod
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: aspm-test
          artifact-id: 11ca354b-97ba-4af3-a173-cedace4e4250
          target-environment: qa
